USE adlister_db;

DROP TABLE IF EXISTS users;

CREATE TABLE users(
      id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY ,
      username VARCHAR(40) NOT NULL,
      email VARCHAR(50) NOT NULL,
      password VARCHAR(30) NOT NULL
);